/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Displays a League of Legends champion card with name and splash art.
     * Stub — logic to be implemented in a later phase.
     */
    interface LolChampionCard {
        /**
          * Champion name
          * @default ""
         */
        "name": string;
        /**
          * URL to the champion splash art
          * @default ""
         */
        "splashArtUrl": string;
    }
}
declare global {
    /**
     * Displays a League of Legends champion card with name and splash art.
     * Stub — logic to be implemented in a later phase.
     */
    interface HTMLLolChampionCardElement extends Components.LolChampionCard, HTMLStencilElement {
    }
    var HTMLLolChampionCardElement: {
        prototype: HTMLLolChampionCardElement;
        new (): HTMLLolChampionCardElement;
    };
    interface HTMLElementTagNameMap {
        "lol-champion-card": HTMLLolChampionCardElement;
    }
}
declare namespace LocalJSX {
    /**
     * Displays a League of Legends champion card with name and splash art.
     * Stub — logic to be implemented in a later phase.
     */
    interface LolChampionCard {
        /**
          * Champion name
          * @default ""
         */
        "name"?: string;
        /**
          * URL to the champion splash art
          * @default ""
         */
        "splashArtUrl"?: string;
    }

    interface LolChampionCardAttributes {
        "name": string;
        "splashArtUrl": string;
    }

    interface IntrinsicElements {
        "lol-champion-card": Omit<LolChampionCard, keyof LolChampionCardAttributes> & { [K in keyof LolChampionCard & keyof LolChampionCardAttributes]?: LolChampionCard[K] } & { [K in keyof LolChampionCard & keyof LolChampionCardAttributes as `attr:${K}`]?: LolChampionCardAttributes[K] } & { [K in keyof LolChampionCard & keyof LolChampionCardAttributes as `prop:${K}`]?: LolChampionCard[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Displays a League of Legends champion card with name and splash art.
             * Stub — logic to be implemented in a later phase.
             */
            "lol-champion-card": LocalJSX.IntrinsicElements["lol-champion-card"] & JSXBase.HTMLAttributes<HTMLLolChampionCardElement>;
        }
    }
}
