// Component type declarations — always available (committed to source).
export type { Components } from "./components";
// React wrappers — generated by `pnpm nx run ui:build` (gitignored).
// Uncomment once @stencil/react-output-target is re-enabled in stencil.config.ts.
// export * from "./react/components";
